# Generated by Django 3.1.1 on 2020-11-26 12:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Checklist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
            ],
            options={
                'db_table': 'checklist',
            },
        ),
        migrations.CreateModel(
            name='ChListSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('checklist', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='otk.checklist')),
            ],
            options={
                'db_table': 'chlistsection',
            },
        ),
        migrations.CreateModel(
            name='OrderConfigSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
            ],
            options={
                'db_table': 'orderconfigsection',
            },
        ),
        migrations.CreateModel(
            name='TMCheckList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UE_Code', models.CharField(blank=True, default='', max_length=20, verbose_name='Шифр(УЭ)')),
                ('TM_Code', models.CharField(blank=True, default='', max_length=20, verbose_name='Шифр (ТМ)')),
                ('Type_KTM_UE', models.CharField(blank=True, default='', max_length=20, verbose_name='Тип КТМиУЭ')),
                ('Number_KTM_UE', models.CharField(blank=True, default='', max_length=20, verbose_name='зав. №')),
                ('passed', models.CharField(choices=[('НЕ принято', 'НЕ принято'), ('Принято', 'Принято')], default='NO', max_length=15, verbose_name='Чек лист телемеханики прошел все проверки')),
            ],
        ),
        migrations.CreateModel(
            name='YesNoChoicePoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('serial_number', models.IntegerField(blank=True, default=0)),
                ('point_value', models.CharField(choices=[('Принято', 'ДА'), ('НЕ Принято', 'НЕТ')], default='НЕ Принято', max_length=15)),
                ('checklist', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='otk.chlistsection')),
                ('order_config', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='otk.orderconfigsection')),
            ],
            options={
                'db_table': 'yesnochoicepoint',
            },
        ),
        migrations.CreateModel(
            name='YBPCheckList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ts_connector', models.CharField(choices=[('Не проверено', 'Не проверено'), ('Не используется', 'Не используется'), ('Принято', 'Принято'), ('Замечания', 'Замечания')], default='Не проверено', max_length=15, verbose_name='подключение цепей ТС вводного выключателя')),
                ('ts_disconnector', models.CharField(choices=[('Не проверено', 'Не проверено'), ('Не используется', 'Не используется'), ('Принято', 'Принято'), ('Замечания', 'Замечания')], default='Не проверено', max_length=15, verbose_name='подключение цепей ТС секционного разъединителя')),
                ('tt', models.CharField(choices=[('Не проверено', 'Не проверено'), ('Не используется', 'Не используется'), ('Принято', 'Принято'), ('Замечания', 'Замечания')], default='Не проверено', max_length=15, verbose_name='трансформаторы тока вводного выключателя (тип, номинал, класс точности, направление Л1-Л2)')),
                ('wire_vv', models.CharField(choices=[('Не проверено', 'Не проверено'), ('Не используется', 'Не используется'), ('Принято', 'Принято'), ('Замечания', 'Замечания')], default='Не проверено', max_length=15, verbose_name='подключение измерительных цепей тока и напряжения ВВ(надежность подключения, маркировка, полярность И1-И2)')),
                ('tt_earth_vv', models.CharField(choices=[('Не проверено', 'Не проверено'), ('Не используется', 'Не используется'), ('Принято', 'Принято'), ('Замечания', 'Замечания')], default='Не проверено', max_length=15, verbose_name='заземление вторичных обмоток ТТ вводного выключателя')),
                ('tt_lines', models.CharField(choices=[('Не проверено', 'Не проверено'), ('Не используется', 'Не используется'), ('Принято', 'Принято'), ('Замечания', 'Замечания')], default='Не проверено', max_length=15, verbose_name='трансформаторы тока отходящих линий (тип, номинал, класс точности, направление Л1-Л2)')),
                ('tt_number', models.CharField(choices=[('Не проверено', 'Не проверено'), ('Не используется', 'Не используется'), ('Принято', 'Принято'), ('Замечания', 'Замечания')], default='Не проверено', max_length=15, verbose_name='Соответствие количества трансформаторов тока проекту')),
                ('vire_ol', models.CharField(choices=[('Не проверено', 'Не проверено'), ('Не используется', 'Не используется'), ('Принято', 'Принято'), ('Замечания', 'Замечания')], default='Не проверено', max_length=15, verbose_name='подключение измерительных цепей тока и напряжения ОЛ(надежность подключения, маркировка, полярность И1-И2)')),
                ('tt_earth_ol', models.CharField(choices=[('Не проверено', 'Не проверено'), ('Не используется', 'Не используется'), ('Принято', 'Принято'), ('Замечания', 'Замечания')], default='Не проверено', max_length=15, verbose_name='заземление вторичных обмоток ТТ отходящих линий')),
                ('passed', models.CharField(choices=[('НЕ принято', 'НЕ принято'), ('Принято', 'Принято')], default='NO', max_length=15, verbose_name='Чек лист УВР прошел все проверки')),
                ('checklist', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='otk.tmchecklist')),
            ],
        ),
        migrations.CreateModel(
            name='SUCheckList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('py', models.CharField(choices=[('Не проверено', 'Не проверено'), ('Не используется', 'Не используется'), ('Принято', 'Принято'), ('Замечания', 'Замечания')], default='Не проверено', max_length=15, verbose_name='ПУ - расположение тип напряжение, ток, дата поверки, маркировка')),
                ('py_number', models.CharField(choices=[('Не проверено', 'Не проверено'), ('Не используется', 'Не используется'), ('Принято', 'Принято'), ('Замечания', 'Замечания')], default='Не проверено', max_length=15, verbose_name='ПУ - количество')),
                ('wire', models.CharField(choices=[('Не проверено', 'Не проверено'), ('Не используется', 'Не используется'), ('Принято', 'Принято'), ('Замечания', 'Замечания')], default='Не проверено', max_length=15, verbose_name='подключение измерительных цепей (правильность, маркировка, надежность)')),
                ('test_block', models.CharField(choices=[('Не проверено', 'Не проверено'), ('Не используется', 'Не используется'), ('Принято', 'Принято'), ('Замечания', 'Замечания')], default='Не проверено', max_length=15, verbose_name='испытательные колодки (количество+резерв, комплектность, правильность расключения, надежность крепления проводников, маркировка)')),
                ('wire_reserve', models.CharField(choices=[('Не проверено', 'Не проверено'), ('Не используется', 'Не используется'), ('Принято', 'Принято'), ('Замечания', 'Замечания')], default='Не проверено', max_length=15, verbose_name='подключение цепей резервного питания')),
                ('rs485_box', models.CharField(choices=[('Не проверено', 'Не проверено'), ('Не используется', 'Не используется'), ('Принято', 'Принято'), ('Замечания', 'Замечания')], default='Не проверено', max_length=15, verbose_name='распределительные коробки RS485 (количество, комплектность)')),
                ('wire_connection', models.CharField(choices=[('Не проверено', 'Не проверено'), ('Не используется', 'Не используется'), ('Принято', 'Принято'), ('Замечания', 'Замечания')], default='Не проверено', max_length=15, verbose_name='подключение кабелей связи (расключение в РИ, подключение к ПУ, то-пология согласно структурной схеме, маркировка)')),
                ('wire_helper', models.CharField(choices=[('Не проверено', 'Не проверено'), ('Не используется', 'Не используется'), ('Принято', 'Принято'), ('Замечания', 'Замечания')], default='Не проверено', max_length=15, verbose_name='вспомогательные цепи (освещения, обогрева))')),
                ('passed', models.CharField(choices=[('НЕ принято', 'НЕ принято'), ('Принято', 'Принято')], default='NO', max_length=15, verbose_name='Чек лист ШУ прошел все проверки')),
                ('checklist', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='otk.tmchecklist')),
            ],
        ),
        migrations.CreateModel(
            name='SubstationTypePoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('serial_number', models.IntegerField(blank=True, default=0)),
                ('point_value', models.CharField(choices=[('БКТП', 'БКТП')], default='БКТП', max_length=15)),
                ('checklist', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='otk.chlistsection')),
                ('order_config', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='otk.orderconfigsection')),
            ],
            options={
                'db_table': 'substationpoint',
            },
        ),
        migrations.CreateModel(
            name='StringPoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('serial_number', models.IntegerField(blank=True, default=0)),
                ('point_value', models.CharField(blank=True, default='', max_length=100)),
                ('checklist', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='otk.chlistsection')),
                ('order_config', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='otk.orderconfigsection')),
            ],
            options={
                'db_table': 'stringpoint',
            },
        ),
        migrations.CreateModel(
            name='SRTMCheckList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creit', models.CharField(choices=[('Не проверено', 'Не проверено'), ('Не используется', 'Не используется'), ('Принято', 'Принято'), ('Замечания', 'Замечания')], default='Не проверено', max_length=15, verbose_name='крейт расширения')),
                ('connections', models.CharField(choices=[('Не проверено', 'Не проверено'), ('Не используется', 'Не используется'), ('Принято', 'Принято'), ('Замечания', 'Замечания')], default='Не проверено', max_length=15, verbose_name='автоматы и предохранители согласно схеме')),
                ('terminal_blocks', models.CharField(choices=[('Не проверено', 'Не проверено'), ('Не используется', 'Не используется'), ('Принято', 'Принято'), ('Замечания', 'Замечания')], default='Не проверено', max_length=15, verbose_name='блоки клемм')),
                ('passed', models.CharField(choices=[('НЕ принято', 'НЕ принято'), ('Принято', 'Принято')], default='NO', max_length=15, verbose_name='Чек лист ШРТМ прошел все проверки')),
                ('checklist', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='otk.tmchecklist')),
            ],
        ),
        migrations.CreateModel(
            name='SKTMCheckList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('controller', models.CharField(choices=[('Не проверено', 'Не проверено'), ('Не используется', 'Не используется'), ('Принято', 'Принято'), ('Замечания', 'Замечания')], default='Не проверено', max_length=15, verbose_name='контроллер')),
                ('connections', models.CharField(choices=[('Не проверено', 'Не проверено'), ('Не используется', 'Не используется'), ('Принято', 'Принято'), ('Замечания', 'Замечания')], default='Не проверено', max_length=15, verbose_name='автоматы, переключатели и предохранители согласно схеме')),
                ('terminal_blocks', models.CharField(choices=[('Не проверено', 'Не проверено'), ('Не используется', 'Не используется'), ('Принято', 'Принято'), ('Замечания', 'Замечания')], default='Не проверено', max_length=15, verbose_name='блоки клемм')),
                ('UZIP', models.CharField(choices=[('Не проверено', 'Не проверено'), ('Не используется', 'Не используется'), ('Принято', 'Принято'), ('Замечания', 'Замечания')], default='Не проверено', max_length=15, verbose_name='УЗИП')),
                ('cable_24', models.CharField(choices=[('Не проверено', 'Не проверено'), ('Не используется', 'Не используется'), ('Принято', 'Принято'), ('Замечания', 'Замечания')], default='Не проверено', max_length=15, verbose_name='система питания =24В (в т.ч. предохранители в блоке батарей)')),
                ('antenna_GPRS', models.CharField(choices=[('Не проверено', 'Не проверено'), ('Не используется', 'Не используется'), ('Принято', 'Принято'), ('Замечания', 'Замечания')], default='Не проверено', max_length=15, verbose_name='антенна GPS')),
                ('antenna_GSM', models.CharField(choices=[('Не проверено', 'Не проверено'), ('Не используется', 'Не используется'), ('Принято', 'Принято'), ('Замечания', 'Замечания')], default='Не проверено', max_length=15, verbose_name='антенна GSM')),
                ('antennas_bracket', models.CharField(choices=[('Не проверено', 'Не проверено'), ('Не используется', 'Не используется'), ('Принято', 'Принято'), ('Замечания', 'Замечания')], default='Не проверено', max_length=15, verbose_name='кронштейны крепления антенн')),
                ('passed', models.CharField(choices=[('НЕ принято', 'НЕ принято'), ('Принято', 'Принято')], default='NO', max_length=15, verbose_name='Чек лист ШКТМ прошел все проверки')),
                ('checklist', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='otk.tmchecklist')),
            ],
        ),
        migrations.CreateModel(
            name='RM6CheckList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial', models.CharField(blank=True, default='', max_length=20, verbose_name='Заводской номер')),
                ('function', models.CharField(blank=True, default='', max_length=6, verbose_name='Состав функций')),
                ('cable_ts', models.CharField(choices=[('Не проверено', 'Не проверено'), ('Не используется', 'Не используется'), ('Принято', 'Принято'), ('Замечания', 'Замечания')], default='Не проверено', max_length=15, verbose_name='подключение кабелей ТС(правильность, маркировка')),
                ('cable_wire', models.CharField(choices=[('Не проверено', 'Не проверено'), ('Не используется', 'Не используется'), ('Принято', 'Принято'), ('Замечания', 'Замечания')], default='Не проверено', max_length=15, verbose_name='подключение кабелей связи к клммам модуля связи (правильность, маркировка')),
                ('wire_patch', models.CharField(choices=[('Не проверено', 'Не проверено'), ('Не используется', 'Не используется'), ('Принято', 'Принято'), ('Замечания', 'Замечания')], default='Не проверено', max_length=15, verbose_name='подключение патч-кордов от модуля связи к VIP, flair')),
                ('cable_220', models.CharField(choices=[('Не проверено', 'Не проверено'), ('Не используется', 'Не используется'), ('Принято', 'Принято'), ('Замечания', 'Замечания')], default='Не проверено', max_length=15, verbose_name='подключение кабелей питания ≈220 В VIP от ШСН')),
                ('cable_24', models.CharField(choices=[('Не проверено', 'Не проверено'), ('Не используется', 'Не используется'), ('Принято', 'Принято'), ('Замечания', 'Замечания')], default='Не проверено', max_length=15, verbose_name='подключение кабелей питания =24 В flair от КТМ')),
                ('cable_earth', models.CharField(choices=[('Не проверено', 'Не проверено'), ('Не используется', 'Не используется'), ('Принято', 'Принято'), ('Замечания', 'Замечания')], default='Не проверено', max_length=15, verbose_name='соединение экранов кабелей связи отдельных участков в единую цепь')),
                ('earth_disable_RM6', models.CharField(choices=[('Не проверено', 'Не проверено'), ('Не используется', 'Не используется'), ('Принято', 'Принято'), ('Замечания', 'Замечания')], default='Не проверено', max_length=15, verbose_name='отсутствие заземления экранов в RM6')),
                ('ts_rm6_controller', models.CharField(choices=[('Не проверено', 'Не проверено'), ('Не используется', 'Не используется'), ('Принято', 'Принято'), ('Замечания', 'Замечания')], default='Не проверено', max_length=15, verbose_name='проверка прохождения ТС от RM6 до дискретных входов контроллера')),
                ('ty_rm6_KTMUE', models.CharField(choices=[('Не проверено', 'Не проверено'), ('Не используется', 'Не используется'), ('Принято', 'Принято'), ('Замечания', 'Замечания')], default='Не проверено', max_length=15, verbose_name='проверка прохождения ТУ от RM6 до КТМиУЭ')),
                ('passed', models.CharField(choices=[('НЕ принято', 'НЕ принято'), ('Принято', 'Принято')], default='NO', max_length=15, verbose_name='Чек лист RM6 прошел все проверки')),
                ('checklist', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='otk.tmchecklist')),
            ],
        ),
        migrations.CreateModel(
            name='OTKOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('man_number', models.IntegerField(unique=True)),
                ('bm_checklist', models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bm_checklist', to='otk.checklist')),
                ('config_section', models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='config_section', to='otk.orderconfigsection')),
                ('doc_checklist', models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='doc_checklist', to='otk.checklist')),
                ('el_checklist', models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='el_checklist', to='otk.checklist')),
                ('sal_checklist', models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sal_checklist', to='otk.checklist')),
                ('tm_checklist', models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='otk.tmchecklist')),
                ('zip_checklist', models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='zip_checklist', to='otk.checklist')),
            ],
        ),
        migrations.CreateModel(
            name='KTMUECheckList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('earth', models.CharField(choices=[('Не проверено', 'Не проверено'), ('Не используется', 'Не используется'), ('Принято', 'Принято'), ('Замечания', 'Замечания')], default='Не проверено', max_length=15, verbose_name='наличие заземления шкафа ШКТМ, ШРТМ')),
                ('inside_wire', models.CharField(choices=[('Не проверено', 'Не проверено'), ('Не используется', 'Не используется'), ('Принято', 'Принято'), ('Замечания', 'Замечания')], default='Не проверено', max_length=15, verbose_name='выполнение внутришкафной разводки (полнота и правильность)')),
                ('inside_earth', models.CharField(choices=[('Не проверено', 'Не проверено'), ('Не используется', 'Не используется'), ('Принято', 'Принято'), ('Замечания', 'Замечания')], default='Не проверено', max_length=15, verbose_name='заземление оборудования шкафов (контроллер, розетка, УЗИП, система питания =24В)')),
                ('marking', models.CharField(choices=[('Не проверено', 'Не проверено'), ('Не используется', 'Не используется'), ('Принято', 'Принято'), ('Замечания', 'Замечания')], default='Не проверено', max_length=15, verbose_name='маркировка оборудования, проводов, клемм')),
                ('outside_wire', models.CharField(choices=[('Не проверено', 'Не проверено'), ('Не используется', 'Не используется'), ('Принято', 'Принято'), ('Замечания', 'Замечания')], default='Не проверено', max_length=15, verbose_name='правильность заводки кабеля в шкаф, крепление кабеля на рейке')),
                ('wire_earth', models.CharField(choices=[('Не проверено', 'Не проверено'), ('Не используется', 'Не используется'), ('Принято', 'Принято'), ('Замечания', 'Замечания')], default='Не проверено', max_length=15, verbose_name='заземление экранов кабелей связи')),
                ('wire_marking', models.CharField(choices=[('Не проверено', 'Не проверено'), ('Не используется', 'Не используется'), ('Принято', 'Принято'), ('Замечания', 'Замечания')], default='Не проверено', max_length=15, verbose_name='подключение кабелей питания к клеммным блокам, маркировка жил')),
                ('wire_ts_marking', models.CharField(choices=[('Не проверено', 'Не проверено'), ('Не используется', 'Не используется'), ('Принято', 'Принято'), ('Замечания', 'Замечания')], default='Не проверено', max_length=15, verbose_name='подключение кабелей ТС к клеммным блокам, маркировка жил')),
                ('wire_ty_marking', models.CharField(choices=[('Не проверено', 'Не проверено'), ('Не используется', 'Не используется'), ('Принято', 'Принято'), ('Замечания', 'Замечания')], default='Не проверено', max_length=15, verbose_name='подключение кабелей ТУ к клеммным блокам, маркировка жил')),
                ('wire_connect_marking', models.CharField(choices=[('Не проверено', 'Не проверено'), ('Не используется', 'Не используется'), ('Принято', 'Принято'), ('Замечания', 'Замечания')], default='Не проверено', max_length=15, verbose_name='подключение кабелей связи к клеммным блокам, маркировка жил')),
                ('sleeve', models.CharField(choices=[('Не проверено', 'Не проверено'), ('Не используется', 'Не используется'), ('Принято', 'Принято'), ('Замечания', 'Замечания')], default='Не проверено', max_length=15, verbose_name='наличие гильз на внешней стене для вывода на фасад кабелей антенн')),
                ('passed', models.CharField(choices=[('НЕ принято', 'НЕ принято'), ('Принято', 'Принято')], default='NO', max_length=15, verbose_name='Чек лист КТМиУЭ прошел все проверки')),
                ('checklist', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='otk.tmchecklist')),
            ],
        ),
        migrations.CreateModel(
            name='IntegerPoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('serial_number', models.IntegerField(blank=True, default=0)),
                ('point_value', models.IntegerField(blank=True, default=0)),
                ('checklist', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='otk.chlistsection')),
                ('order_config', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='otk.orderconfigsection')),
            ],
            options={
                'db_table': 'integerpoint',
            },
        ),
        migrations.CreateModel(
            name='FourChoicePoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('serial_number', models.IntegerField(blank=True, default=0)),
                ('point_value', models.CharField(choices=[('Не проверено', 'Не проверено'), ('Не используется', 'Не используется'), ('Принято', 'Принято'), ('Коментарий', 'Коментарий')], default='Не проверено', max_length=15)),
                ('comment', models.CharField(blank=True, default='', max_length=200, verbose_name='Коментарий')),
                ('checklist', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='otk.chlistsection')),
                ('order_config', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='otk.orderconfigsection')),
            ],
            options={
                'db_table': 'fourchoicepoint',
            },
        ),
    ]
