# Generated by Django 3.1.1 on 2020-10-26 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otk', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otkchecklist',
            name='SKTM',
            field=models.CharField(choices=[('NOT_TESTED', 'Не проверено'), ('UNUSED', 'Не используется'), ('ACCEPTED', 'Принято'), ('DECLINE', 'Замечания')], default='NOT_TESTED', max_length=10),
        ),
    ]
