# Generated by Django 3.1.1 on 2020-12-03 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otk', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yesnochoicepoint',
            name='point_value',
            field=models.CharField(choices=[('Пройдены', 'Пройдены'), ('Не Пройдены', 'Не Пройдены')], default='Не Пройдены', max_length=15),
        ),
    ]
