# Generated by Django 3.1.1 on 2020-11-27 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('otk', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='substationtypepoint',
            table='substationtypepoint',
        ),
    ]
