# Generated by Django 3.1.1 on 2020-11-27 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('otk', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fourchoicepoint',
            old_name='checklist',
            new_name='checklist_section',
        ),
        migrations.RenameField(
            model_name='integerpoint',
            old_name='checklist',
            new_name='checklist_section',
        ),
        migrations.RenameField(
            model_name='stringpoint',
            old_name='checklist',
            new_name='checklist_section',
        ),
        migrations.RenameField(
            model_name='substationtypepoint',
            old_name='checklist',
            new_name='checklist_section',
        ),
        migrations.RenameField(
            model_name='yesnochoicepoint',
            old_name='checklist',
            new_name='checklist_section',
        ),
    ]
