# Generated by Django 3.1.1 on 2020-12-04 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('otk', '0002_auto_20201203_1732'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rm6checklist',
            name='checklist',
        ),
        migrations.RemoveField(
            model_name='sktmchecklist',
            name='checklist',
        ),
        migrations.RemoveField(
            model_name='srtmchecklist',
            name='checklist',
        ),
        migrations.RemoveField(
            model_name='suchecklist',
            name='checklist',
        ),
        migrations.RemoveField(
            model_name='ybpchecklist',
            name='checklist',
        ),
        migrations.DeleteModel(
            name='KTMUECheckList',
        ),
        migrations.DeleteModel(
            name='RM6CheckList',
        ),
        migrations.DeleteModel(
            name='SKTMCheckList',
        ),
        migrations.DeleteModel(
            name='SRTMCheckList',
        ),
        migrations.DeleteModel(
            name='SUCheckList',
        ),
        migrations.DeleteModel(
            name='TMCheckList',
        ),
        migrations.DeleteModel(
            name='YBPCheckList',
        ),
    ]
