# Generated by Django 3.1.1 on 2020-10-26 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otk', '0003_otkchecklist_code_ue'),
    ]

    operations = [
        migrations.CreateModel(
            name='TMCheckList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('Code_UE', models.CharField(blank=True, max_length=10)),
                ('Code_TM', models.CharField(blank=True, max_length=10)),
                ('Type_KTM_UE', models.CharField(blank=True, max_length=10)),
                ('Number_KTM_UE', models.CharField(blank=True, max_length=10)),
                ('SKTM', models.CharField(choices=[('NOT_TESTED', 'Не проверено'), ('UNUSED', 'Не используется'), ('ACCEPTED', 'Принято'), ('DECLINE', 'Замечания')], default='NOT_TESTED', max_length=10)),
            ],
        ),
        migrations.DeleteModel(
            name='OtkCheckList',
        ),
    ]
