# Generated by Django 3.1.1 on 2020-10-26 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('otk', '0004_auto_20201026_1619'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tmchecklist',
            old_name='title',
            new_name='man_number',
        ),
    ]
