# Generated by Django 3.1.1 on 2020-10-26 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otk', '0005_auto_20201026_1622'),
    ]

    operations = [
        migrations.AddField(
            model_name='tmchecklist',
            name='SKTM_GSM_antenna',
            field=models.CharField(choices=[('NOT_TESTED', 'Не проверено'), ('UNUSED', 'Не используется'), ('ACCEPTED', 'Принято'), ('DECLINE', 'Замечания')], default='NOT_TESTED', max_length=10),
        ),
        migrations.AddField(
            model_name='tmchecklist',
            name='SKTM_UZIP',
            field=models.CharField(choices=[('NOT_TESTED', 'Не проверено'), ('UNUSED', 'Не используется'), ('ACCEPTED', 'Принято'), ('DECLINE', 'Замечания')], default='NOT_TESTED', max_length=10),
        ),
        migrations.AddField(
            model_name='tmchecklist',
            name='SKTM_antennas_bracket',
            field=models.CharField(choices=[('NOT_TESTED', 'Не проверено'), ('UNUSED', 'Не используется'), ('ACCEPTED', 'Принято'), ('DECLINE', 'Замечания')], default='NOT_TESTED', max_length=10),
        ),
        migrations.AddField(
            model_name='tmchecklist',
            name='SKTM_commutations',
            field=models.CharField(choices=[('NOT_TESTED', 'Не проверено'), ('UNUSED', 'Не используется'), ('ACCEPTED', 'Принято'), ('DECLINE', 'Замечания')], default='NOT_TESTED', max_length=10),
        ),
        migrations.AddField(
            model_name='tmchecklist',
            name='SKTM_crait',
            field=models.CharField(choices=[('NOT_TESTED', 'Не проверено'), ('UNUSED', 'Не используется'), ('ACCEPTED', 'Принято'), ('DECLINE', 'Замечания')], default='NOT_TESTED', max_length=10),
        ),
        migrations.AddField(
            model_name='tmchecklist',
            name='SKTM_klemmas_blocks',
            field=models.CharField(choices=[('NOT_TESTED', 'Не проверено'), ('UNUSED', 'Не используется'), ('ACCEPTED', 'Принято'), ('DECLINE', 'Замечания')], default='NOT_TESTED', max_length=10),
        ),
        migrations.AddField(
            model_name='tmchecklist',
            name='SKTM_kontroller',
            field=models.CharField(choices=[('NOT_TESTED', 'Не проверено'), ('UNUSED', 'Не используется'), ('ACCEPTED', 'Принято'), ('DECLINE', 'Замечания')], default='NOT_TESTED', max_length=10),
        ),
        migrations.AddField(
            model_name='tmchecklist',
            name='SKTM_supply',
            field=models.CharField(choices=[('NOT_TESTED', 'Не проверено'), ('UNUSED', 'Не используется'), ('ACCEPTED', 'Принято'), ('DECLINE', 'Замечания')], default='NOT_TESTED', max_length=10),
        ),
        migrations.AlterField(
            model_name='tmchecklist',
            name='SKTM',
            field=models.CharField(choices=[('NOT_TESTED', 'Не проверено'), ('UNUSED', 'Не используется'), ('ACCEPTED', 'Принято'), ('DECLINE', 'Замечания')], default='UNUSED', max_length=10),
        ),
    ]
