# Generated by Django 3.1.1 on 2020-10-27 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otk', '0006_auto_20201026_1732'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tmchecklist',
            old_name='SKTM_crait',
            new_name='SKTM_GPS_antenna',
        ),
        migrations.AddField(
            model_name='tmchecklist',
            name='SRTM',
            field=models.CharField(choices=[('NOT_TESTED', 'Не проверено'), ('UNUSED', 'Не используется'), ('ACCEPTED', 'Принято'), ('DECLINE', 'Замечания')], default='UNUSED', max_length=10),
        ),
        migrations.AddField(
            model_name='tmchecklist',
            name='SRTM_commutations',
            field=models.CharField(choices=[('NOT_TESTED', 'Не проверено'), ('UNUSED', 'Не используется'), ('ACCEPTED', 'Принято'), ('DECLINE', 'Замечания')], default='NOT_TESTED', max_length=10),
        ),
        migrations.AddField(
            model_name='tmchecklist',
            name='SRTM_crait',
            field=models.CharField(choices=[('NOT_TESTED', 'Не проверено'), ('UNUSED', 'Не используется'), ('ACCEPTED', 'Принято'), ('DECLINE', 'Замечания')], default='NOT_TESTED', max_length=10),
        ),
        migrations.AddField(
            model_name='tmchecklist',
            name='SRTM_klemmas_blocks',
            field=models.CharField(choices=[('NOT_TESTED', 'Не проверено'), ('UNUSED', 'Не используется'), ('ACCEPTED', 'Принято'), ('DECLINE', 'Замечания')], default='NOT_TESTED', max_length=10),
        ),
    ]
