# Generated by Django 3.1.1 on 2020-10-28 14:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('otk', '0008_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='OTKOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('man_number', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='tmchecklist',
            name='Code_TM',
        ),
        migrations.RemoveField(
            model_name='tmchecklist',
            name='Code_UE',
        ),
        migrations.RemoveField(
            model_name='tmchecklist',
            name='SKTM',
        ),
        migrations.RemoveField(
            model_name='tmchecklist',
            name='SKTM_GPS_antenna',
        ),
        migrations.RemoveField(
            model_name='tmchecklist',
            name='SKTM_GSM_antenna',
        ),
        migrations.RemoveField(
            model_name='tmchecklist',
            name='SKTM_UZIP',
        ),
        migrations.RemoveField(
            model_name='tmchecklist',
            name='SKTM_antennas_bracket',
        ),
        migrations.RemoveField(
            model_name='tmchecklist',
            name='SKTM_commutations',
        ),
        migrations.RemoveField(
            model_name='tmchecklist',
            name='SKTM_klemmas_blocks',
        ),
        migrations.RemoveField(
            model_name='tmchecklist',
            name='SKTM_kontroller',
        ),
        migrations.RemoveField(
            model_name='tmchecklist',
            name='SKTM_supply',
        ),
        migrations.RemoveField(
            model_name='tmchecklist',
            name='SRTM',
        ),
        migrations.RemoveField(
            model_name='tmchecklist',
            name='SRTM_commutations',
        ),
        migrations.RemoveField(
            model_name='tmchecklist',
            name='SRTM_crait',
        ),
        migrations.RemoveField(
            model_name='tmchecklist',
            name='SRTM_klemmas_blocks',
        ),
        migrations.RemoveField(
            model_name='tmchecklist',
            name='man_number',
        ),
        migrations.AddField(
            model_name='tmchecklist',
            name='TM_Code',
            field=models.CharField(default=None, max_length=20, verbose_name='Шифр (ТМ)'),
        ),
        migrations.AddField(
            model_name='tmchecklist',
            name='UE_Code',
            field=models.CharField(default=None, max_length=20, verbose_name='Шифр(УЭ'),
        ),
        migrations.AlterField(
            model_name='tmchecklist',
            name='Number_KTM_UE',
            field=models.CharField(default=None, max_length=20, verbose_name='зав. №'),
        ),
        migrations.AlterField(
            model_name='tmchecklist',
            name='Type_KTM_UE',
            field=models.CharField(default=None, max_length=20, verbose_name='Тип КТМиУЭ'),
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.AddField(
            model_name='otkorder',
            name='tm_checklist',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='otk.tmchecklist'),
        ),
    ]
