# Generated by Django 3.1.1 on 2020-10-28 15:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('otk', '0010_auto_20201028_1802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otkorder',
            name='tm_checklist',
            field=models.OneToOneField(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='otk.tmchecklist'),
        ),
    ]
