# Generated by Django 3.1.1 on 2020-10-28 15:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('otk', '0011_auto_20201028_1851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otkorder',
            name='tm_checklist',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to='otk.tmchecklist'),
        ),
        migrations.AlterField(
            model_name='tmchecklist',
            name='Number_KTM_UE',
            field=models.CharField(blank=True, default=None, max_length=20, verbose_name='зав. №'),
        ),
        migrations.AlterField(
            model_name='tmchecklist',
            name='TM_Code',
            field=models.CharField(blank=True, default=None, max_length=20, verbose_name='Шифр (ТМ)'),
        ),
        migrations.AlterField(
            model_name='tmchecklist',
            name='Type_KTM_UE',
            field=models.CharField(blank=True, default=None, max_length=20, verbose_name='Тип КТМиУЭ'),
        ),
        migrations.AlterField(
            model_name='tmchecklist',
            name='UE_Code',
            field=models.CharField(blank=True, default=None, max_length=20, verbose_name='Шифр(УЭ)'),
        ),
    ]
