# Generated by Django 3.1.1 on 2020-10-29 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otk', '0012_auto_20201028_1853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tmchecklist',
            name='Number_KTM_UE',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='зав. №'),
        ),
        migrations.AlterField(
            model_name='tmchecklist',
            name='TM_Code',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Шифр (ТМ)'),
        ),
        migrations.AlterField(
            model_name='tmchecklist',
            name='Type_KTM_UE',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Тип КТМиУЭ'),
        ),
        migrations.AlterField(
            model_name='tmchecklist',
            name='UE_Code',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Шифр(УЭ)'),
        ),
    ]
