# Generated by Django 3.1.1 on 2020-10-29 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('otk', '0013_auto_20201029_1530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otkorder',
            name='tm_checklist',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='otk.tmchecklist'),
        ),
    ]
