# Generated by Django 3.1.1 on 2020-11-02 05:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('otk', '0016_rm6checklist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rm6checklist',
            name='checklist',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='otk.tmchecklist'),
        ),
    ]
