# Generated by Django 3.1.1 on 2020-11-03 07:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('otk', '0018_onemoretables'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otkorder',
            name='tm_checklist',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='otk.tmchecklist'),
        ),
    ]
