# Generated by Django 3.1.1 on 2020-11-03 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otk', '0019_auto_20201103_1032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otkorder',
            name='man_number',
            field=models.IntegerField(unique=True),
        ),
    ]
