# Generated by Django 3.1.1 on 2020-11-03 08:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('otk', '0020_auto_20201103_1058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onemoretables',
            name='checklist',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='otk.tmchecklist'),
        ),
    ]
