# Generated by Django 3.1.1 on 2020-11-03 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('otk', '0021_auto_20201103_1104'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OneMoreTables',
        ),
    ]
