# Generated by Django 3.1.1 on 2020-11-03 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otk', '0022_delete_onemoretables'),
    ]

    operations = [
        migrations.AddField(
            model_name='rm6checklist',
            name='cable_ts',
            field=models.CharField(blank=True, choices=[('NOT_TESTED', 'Не проверено'), ('UNUSED', 'Не используется'), ('ACCEPTED', 'Принято'), ('DECLINE', 'Замечания')], default='UNUSED', max_length=15),
        ),
        migrations.AddField(
            model_name='rm6checklist',
            name='function',
            field=models.CharField(blank=True, default='', max_length=6, verbose_name='Состав функций'),
        ),
    ]
