# Generated by Django 3.1.1 on 2020-11-03 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otk', '0023_auto_20201103_1337'),
    ]

    operations = [
        migrations.AddField(
            model_name='rm6checklist',
            name='cable_220',
            field=models.CharField(choices=[('NOT_TESTED', 'Не проверено'), ('UNUSED', 'Не используется'), ('ACCEPTED', 'Принято'), ('DECLINE', 'Замечания')], default='UNUSED', max_length=15, verbose_name='подключение кабелей питания ≈220 В VIP от ШСН'),
        ),
        migrations.AddField(
            model_name='rm6checklist',
            name='cable_24',
            field=models.CharField(choices=[('NOT_TESTED', 'Не проверено'), ('UNUSED', 'Не используется'), ('ACCEPTED', 'Принято'), ('DECLINE', 'Замечания')], default='UNUSED', max_length=15, verbose_name='подключение кабелей питания =24 В flair от КТМ'),
        ),
        migrations.AddField(
            model_name='rm6checklist',
            name='cable_earth',
            field=models.CharField(choices=[('NOT_TESTED', 'Не проверено'), ('UNUSED', 'Не используется'), ('ACCEPTED', 'Принято'), ('DECLINE', 'Замечания')], default='UNUSED', max_length=15, verbose_name='соединение экранов кабелей связи отдельных участков в единую цепь'),
        ),
        migrations.AddField(
            model_name='rm6checklist',
            name='cable_wire',
            field=models.CharField(choices=[('NOT_TESTED', 'Не проверено'), ('UNUSED', 'Не используется'), ('ACCEPTED', 'Принято'), ('DECLINE', 'Замечания')], default='UNUSED', max_length=15, verbose_name='подключение кабелей связи к клммам модуля связи (правильность, маркировка'),
        ),
        migrations.AddField(
            model_name='rm6checklist',
            name='earth_disable_RM6',
            field=models.CharField(choices=[('NOT_TESTED', 'Не проверено'), ('UNUSED', 'Не используется'), ('ACCEPTED', 'Принято'), ('DECLINE', 'Замечания')], default='UNUSED', max_length=15, verbose_name='отсутствие заземления экранов в RM6'),
        ),
        migrations.AddField(
            model_name='rm6checklist',
            name='passed',
            field=models.CharField(choices=[('NO', 'НЕ принято'), ('YES', 'Принято')], default='NO', max_length=15, verbose_name='подключение кабелей связи к клммам модуля связи (правильность, маркировка'),
        ),
        migrations.AddField(
            model_name='rm6checklist',
            name='wire_patch',
            field=models.CharField(choices=[('NOT_TESTED', 'Не проверено'), ('UNUSED', 'Не используется'), ('ACCEPTED', 'Принято'), ('DECLINE', 'Замечания')], default='UNUSED', max_length=15, verbose_name='подключение патч-кордов от модуля связи к VIP, flair'),
        ),
        migrations.AddField(
            model_name='tmchecklist',
            name='passed',
            field=models.CharField(choices=[('NO', 'НЕ принято'), ('YES', 'Принято')], default='NO', max_length=15, verbose_name='подключение кабелей связи к клммам модуля связи (правильность, маркировка'),
        ),
        migrations.AlterField(
            model_name='rm6checklist',
            name='cable_ts',
            field=models.CharField(choices=[('NOT_TESTED', 'Не проверено'), ('UNUSED', 'Не используется'), ('ACCEPTED', 'Принято'), ('DECLINE', 'Замечания')], default='UNUSED', max_length=15, verbose_name='подключение кабелей ТС(правильность, маркировка'),
        ),
    ]
