# Generated by Django 3.1.1 on 2020-11-03 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otk', '0024_auto_20201103_1403'),
    ]

    operations = [
        migrations.AddField(
            model_name='rm6checklist',
            name='ts_rm6_controller',
            field=models.CharField(choices=[('NOT_TESTED', 'Не проверено'), ('UNUSED', 'Не используется'), ('ACCEPTED', 'Принято'), ('DECLINE', 'Замечания')], default='UNUSED', max_length=15, verbose_name='проверка прохождения ТС от RM6 до дискретных входов контроллера'),
        ),
        migrations.AddField(
            model_name='rm6checklist',
            name='ty_rm6_KTMUE',
            field=models.CharField(choices=[('NOT_TESTED', 'Не проверено'), ('UNUSED', 'Не используется'), ('ACCEPTED', 'Принято'), ('DECLINE', 'Замечания')], default='UNUSED', max_length=15, verbose_name='проверка прохождения ТУ от RM6 до КТМиУЭ'),
        ),
        migrations.AlterField(
            model_name='rm6checklist',
            name='passed',
            field=models.CharField(choices=[('NO', 'НЕ принято'), ('YES', 'Принято')], default='NO', max_length=15, verbose_name='Чек лист RM6 прошел все проверки'),
        ),
        migrations.AlterField(
            model_name='tmchecklist',
            name='passed',
            field=models.CharField(choices=[('NO', 'НЕ принято'), ('YES', 'Принято')], default='NO', max_length=15, verbose_name='Чек лист телемеханики прошел все проверки'),
        ),
    ]
