# Generated by Django 3.1.1 on 2020-11-03 13:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('otk', '0026_sktmchecklist'),
    ]

    operations = [
        migrations.CreateModel(
            name='SRTMCheckList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creit', models.CharField(choices=[('NOT_TESTED', 'Не проверено'), ('UNUSED', 'Не используется'), ('ACCEPTED', 'Принято'), ('DECLINE', 'Замечания')], default='UNUSED', max_length=15, verbose_name='крейт расширения')),
                ('connections', models.CharField(choices=[('NOT_TESTED', 'Не проверено'), ('UNUSED', 'Не используется'), ('ACCEPTED', 'Принято'), ('DECLINE', 'Замечания')], default='UNUSED', max_length=15, verbose_name='автоматы и предохранители согласно схеме')),
                ('terminal_blocks', models.CharField(choices=[('NOT_TESTED', 'Не проверено'), ('UNUSED', 'Не используется'), ('ACCEPTED', 'Принято'), ('DECLINE', 'Замечания')], default='UNUSED', max_length=15, verbose_name='блоки клемм')),
                ('checklist', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='otk.tmchecklist')),
            ],
        ),
    ]
