# Generated by Django 3.1.1 on 2020-11-03 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('otk', '0027_srtmchecklist'),
    ]

    operations = [
        migrations.AddField(
            model_name='srtmchecklist',
            name='passed',
            field=models.CharField(choices=[('NO', 'НЕ принято'), ('YES', 'Принято')], default='NO', max_length=15, verbose_name='Чек лист ШРТМ прошел все проверки'),
        ),
        migrations.CreateModel(
            name='KTMUECheckList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('earth', models.CharField(choices=[('NOT_TESTED', 'Не проверено'), ('UNUSED', 'Не используется'), ('ACCEPTED', 'Принято'), ('DECLINE', 'Замечания')], default='UNUSED', max_length=15, verbose_name='наличие заземления шкафа ШКТМ, ШРТМ')),
                ('inside_wire', models.CharField(choices=[('NOT_TESTED', 'Не проверено'), ('UNUSED', 'Не используется'), ('ACCEPTED', 'Принято'), ('DECLINE', 'Замечания')], default='UNUSED', max_length=15, verbose_name='выполнение внутришкафной разводки (полнота и правильность)')),
                ('inside_earth', models.CharField(choices=[('NOT_TESTED', 'Не проверено'), ('UNUSED', 'Не используется'), ('ACCEPTED', 'Принято'), ('DECLINE', 'Замечания')], default='UNUSED', max_length=15, verbose_name='заземление оборудования шкафов (контроллер, розетка, УЗИП, система питания =24В)')),
                ('marking', models.CharField(choices=[('NOT_TESTED', 'Не проверено'), ('UNUSED', 'Не используется'), ('ACCEPTED', 'Принято'), ('DECLINE', 'Замечания')], default='UNUSED', max_length=15, verbose_name='маркировка оборудования, проводов, клемм')),
                ('outside_wire', models.CharField(choices=[('NOT_TESTED', 'Не проверено'), ('UNUSED', 'Не используется'), ('ACCEPTED', 'Принято'), ('DECLINE', 'Замечания')], default='UNUSED', max_length=15, verbose_name='правильность заводки кабеля в шкаф, крепление кабеля на рейке')),
                ('wire_earth', models.CharField(choices=[('NOT_TESTED', 'Не проверено'), ('UNUSED', 'Не используется'), ('ACCEPTED', 'Принято'), ('DECLINE', 'Замечания')], default='UNUSED', max_length=15, verbose_name='заземление экранов кабелей связи')),
                ('wire_marking', models.CharField(choices=[('NOT_TESTED', 'Не проверено'), ('UNUSED', 'Не используется'), ('ACCEPTED', 'Принято'), ('DECLINE', 'Замечания')], default='UNUSED', max_length=15, verbose_name='подключение кабелей питания к клеммным блокам, маркировка жил')),
                ('wire_ts_marking', models.CharField(choices=[('NOT_TESTED', 'Не проверено'), ('UNUSED', 'Не используется'), ('ACCEPTED', 'Принято'), ('DECLINE', 'Замечания')], default='UNUSED', max_length=15, verbose_name='подключение кабелей ТС к клеммным блокам, маркировка жил')),
                ('wire_ty_marking', models.CharField(choices=[('NOT_TESTED', 'Не проверено'), ('UNUSED', 'Не используется'), ('ACCEPTED', 'Принято'), ('DECLINE', 'Замечания')], default='UNUSED', max_length=15, verbose_name='подключение кабелей ТУ к клеммным блокам, маркировка жил')),
                ('wire_connect_marking', models.CharField(choices=[('NOT_TESTED', 'Не проверено'), ('UNUSED', 'Не используется'), ('ACCEPTED', 'Принято'), ('DECLINE', 'Замечания')], default='UNUSED', max_length=15, verbose_name='подключение кабелей связи к клеммным блокам, маркировка жил')),
                ('sleeve', models.CharField(choices=[('NOT_TESTED', 'Не проверено'), ('UNUSED', 'Не используется'), ('ACCEPTED', 'Принято'), ('DECLINE', 'Замечания')], default='UNUSED', max_length=15, verbose_name='наличие гильз на внешней стене для вывода на фасад кабелей антенн')),
                ('passed', models.CharField(choices=[('NO', 'НЕ принято'), ('YES', 'Принято')], default='NO', max_length=15, verbose_name='Чек лист КТМиУЭ прошел все проверки')),
                ('checklist', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='otk.tmchecklist')),
            ],
        ),
    ]
