# Generated by Django 3.1.1 on 2020-11-03 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('otk', '0028_auto_20201103_1755'),
    ]

    operations = [
        migrations.CreateModel(
            name='YBPCheckList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ts_connector', models.CharField(choices=[('NOT_TESTED', 'Не проверено'), ('UNUSED', 'Не используется'), ('ACCEPTED', 'Принято'), ('DECLINE', 'Замечания')], default='UNUSED', max_length=15, verbose_name='подключение цепей ТС вводного выключателя')),
                ('ts_disconnector', models.CharField(choices=[('NOT_TESTED', 'Не проверено'), ('UNUSED', 'Не используется'), ('ACCEPTED', 'Принято'), ('DECLINE', 'Замечания')], default='UNUSED', max_length=15, verbose_name='подключение цепей ТС секционного разъединителя')),
                ('tt', models.CharField(choices=[('NOT_TESTED', 'Не проверено'), ('UNUSED', 'Не используется'), ('ACCEPTED', 'Принято'), ('DECLINE', 'Замечания')], default='UNUSED', max_length=15, verbose_name='трансформаторы тока вводного выключателя (тип, номинал, класс точности, направление Л1-Л2)')),
                ('wire_vv', models.CharField(choices=[('NOT_TESTED', 'Не проверено'), ('UNUSED', 'Не используется'), ('ACCEPTED', 'Принято'), ('DECLINE', 'Замечания')], default='UNUSED', max_length=15, verbose_name='подключение измерительных цепей тока и напряжения ВВ(надежность подключения, маркировка, полярность И1-И2)')),
                ('tt_earth_vv', models.CharField(choices=[('NOT_TESTED', 'Не проверено'), ('UNUSED', 'Не используется'), ('ACCEPTED', 'Принято'), ('DECLINE', 'Замечания')], default='UNUSED', max_length=15, verbose_name='заземление вторичных обмоток ТТ вводного выключателя')),
                ('tt_lines', models.CharField(choices=[('NOT_TESTED', 'Не проверено'), ('UNUSED', 'Не используется'), ('ACCEPTED', 'Принято'), ('DECLINE', 'Замечания')], default='UNUSED', max_length=15, verbose_name='трансформаторы тока отходящих линий (тип, номинал, класс точности, направление Л1-Л2)')),
                ('tt_number', models.CharField(choices=[('NOT_TESTED', 'Не проверено'), ('UNUSED', 'Не используется'), ('ACCEPTED', 'Принято'), ('DECLINE', 'Замечания')], default='UNUSED', max_length=15, verbose_name='Соответствие количества трансформаторов тока проекту')),
                ('vire_ol', models.CharField(choices=[('NOT_TESTED', 'Не проверено'), ('UNUSED', 'Не используется'), ('ACCEPTED', 'Принято'), ('DECLINE', 'Замечания')], default='UNUSED', max_length=15, verbose_name='подключение измерительных цепей тока и напряжения ОЛ(надежность подключения, маркировка, полярность И1-И2)')),
                ('tt_earth_ol', models.CharField(choices=[('NOT_TESTED', 'Не проверено'), ('UNUSED', 'Не используется'), ('ACCEPTED', 'Принято'), ('DECLINE', 'Замечания')], default='UNUSED', max_length=15, verbose_name='заземление вторичных обмоток ТТ отходящих линий')),
                ('passed', models.CharField(choices=[('NO', 'НЕ принято'), ('YES', 'Принято')], default='NO', max_length=15, verbose_name='Чек лист УВР прошел все проверки')),
                ('checklist', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='otk.tmchecklist')),
            ],
        ),
    ]
