# Generated by Django 3.1.1 on 2020-11-03 16:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('otk', '0029_ybpchecklist'),
    ]

    operations = [
        migrations.CreateModel(
            name='SUCheckList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('py', models.CharField(choices=[('NOT_TESTED', 'Не проверено'), ('UNUSED', 'Не используется'), ('ACCEPTED', 'Принято'), ('DECLINE', 'Замечания')], default='UNUSED', max_length=15, verbose_name='ПУ - расположение тип напряжение, ток, дата поверки, маркировка')),
                ('py_number', models.CharField(choices=[('NOT_TESTED', 'Не проверено'), ('UNUSED', 'Не используется'), ('ACCEPTED', 'Принято'), ('DECLINE', 'Замечания')], default='UNUSED', max_length=15, verbose_name='ПУ - количество')),
                ('wire', models.CharField(choices=[('NOT_TESTED', 'Не проверено'), ('UNUSED', 'Не используется'), ('ACCEPTED', 'Принято'), ('DECLINE', 'Замечания')], default='UNUSED', max_length=15, verbose_name='подключение измерительных цепей (правильность, маркировка, надежность)')),
                ('test_block', models.CharField(choices=[('NOT_TESTED', 'Не проверено'), ('UNUSED', 'Не используется'), ('ACCEPTED', 'Принято'), ('DECLINE', 'Замечания')], default='UNUSED', max_length=15, verbose_name='испытательные колодки (количество+резерв, комплектность, правильность расключения, надежность крепления проводников, маркировка)')),
                ('wire_reserve', models.CharField(choices=[('NOT_TESTED', 'Не проверено'), ('UNUSED', 'Не используется'), ('ACCEPTED', 'Принято'), ('DECLINE', 'Замечания')], default='UNUSED', max_length=15, verbose_name='подключение цепей резервного питания')),
                ('rs485_box', models.CharField(choices=[('NOT_TESTED', 'Не проверено'), ('UNUSED', 'Не используется'), ('ACCEPTED', 'Принято'), ('DECLINE', 'Замечания')], default='UNUSED', max_length=15, verbose_name='распределительные коробки RS485 (количество, комплектность)')),
                ('wire_connection', models.CharField(choices=[('NOT_TESTED', 'Не проверено'), ('UNUSED', 'Не используется'), ('ACCEPTED', 'Принято'), ('DECLINE', 'Замечания')], default='UNUSED', max_length=15, verbose_name='подключение кабелей связи (расключение в РИ, подключение к ПУ, то-пология согласно структурной схеме, маркировка)')),
                ('wire_helper', models.CharField(choices=[('NOT_TESTED', 'Не проверено'), ('UNUSED', 'Не используется'), ('ACCEPTED', 'Принято'), ('DECLINE', 'Замечания')], default='UNUSED', max_length=15, verbose_name='вспомогательные цепи (освещения, обогрева))')),
                ('passed', models.CharField(choices=[('NO', 'НЕ принято'), ('YES', 'Принято')], default='NO', max_length=15, verbose_name='Чек лист ШУ прошел все проверки')),
                ('checklist', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='otk.tmchecklist')),
            ],
        ),
    ]
