# Generated by Django 3.1.1 on 2020-11-13 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otk', '0030_suchecklist'),
    ]

    operations = [
        migrations.AddField(
            model_name='otkorder',
            name='rm_number',
            field=models.IntegerField(default=4, unique=True),
        ),
        migrations.AddField(
            model_name='otkorder',
            name='su_number',
            field=models.IntegerField(default=2, unique=True),
        ),
        migrations.AddField(
            model_name='otkorder',
            name='ybp_number',
            field=models.IntegerField(default=2, unique=True),
        ),
        migrations.AlterField(
            model_name='ktmuechecklist',
            name='earth',
            field=models.CharField(choices=[('Не проверено', 'Не проверено'), ('Не используется', 'Не используется'), ('Принято', 'Принято'), ('Замечания', 'Замечания')], default='Не проверено', max_length=15, verbose_name='наличие заземления шкафа ШКТМ, ШРТМ'),
        ),
        migrations.AlterField(
            model_name='ktmuechecklist',
            name='inside_earth',
            field=models.CharField(choices=[('Не проверено', 'Не проверено'), ('Не используется', 'Не используется'), ('Принято', 'Принято'), ('Замечания', 'Замечания')], default='Не проверено', max_length=15, verbose_name='заземление оборудования шкафов (контроллер, розетка, УЗИП, система питания =24В)'),
        ),
        migrations.AlterField(
            model_name='ktmuechecklist',
            name='inside_wire',
            field=models.CharField(choices=[('Не проверено', 'Не проверено'), ('Не используется', 'Не используется'), ('Принято', 'Принято'), ('Замечания', 'Замечания')], default='Не проверено', max_length=15, verbose_name='выполнение внутришкафной разводки (полнота и правильность)'),
        ),
        migrations.AlterField(
            model_name='ktmuechecklist',
            name='marking',
            field=models.CharField(choices=[('Не проверено', 'Не проверено'), ('Не используется', 'Не используется'), ('Принято', 'Принято'), ('Замечания', 'Замечания')], default='Не проверено', max_length=15, verbose_name='маркировка оборудования, проводов, клемм'),
        ),
        migrations.AlterField(
            model_name='ktmuechecklist',
            name='outside_wire',
            field=models.CharField(choices=[('Не проверено', 'Не проверено'), ('Не используется', 'Не используется'), ('Принято', 'Принято'), ('Замечания', 'Замечания')], default='Не проверено', max_length=15, verbose_name='правильность заводки кабеля в шкаф, крепление кабеля на рейке'),
        ),
        migrations.AlterField(
            model_name='ktmuechecklist',
            name='passed',
            field=models.CharField(choices=[('НЕ принято', 'НЕ принято'), ('Принято', 'Принято')], default='NO', max_length=15, verbose_name='Чек лист КТМиУЭ прошел все проверки'),
        ),
        migrations.AlterField(
            model_name='ktmuechecklist',
            name='sleeve',
            field=models.CharField(choices=[('Не проверено', 'Не проверено'), ('Не используется', 'Не используется'), ('Принято', 'Принято'), ('Замечания', 'Замечания')], default='Не проверено', max_length=15, verbose_name='наличие гильз на внешней стене для вывода на фасад кабелей антенн'),
        ),
        migrations.AlterField(
            model_name='ktmuechecklist',
            name='wire_connect_marking',
            field=models.CharField(choices=[('Не проверено', 'Не проверено'), ('Не используется', 'Не используется'), ('Принято', 'Принято'), ('Замечания', 'Замечания')], default='Не проверено', max_length=15, verbose_name='подключение кабелей связи к клеммным блокам, маркировка жил'),
        ),
        migrations.AlterField(
            model_name='ktmuechecklist',
            name='wire_earth',
            field=models.CharField(choices=[('Не проверено', 'Не проверено'), ('Не используется', 'Не используется'), ('Принято', 'Принято'), ('Замечания', 'Замечания')], default='Не проверено', max_length=15, verbose_name='заземление экранов кабелей связи'),
        ),
        migrations.AlterField(
            model_name='ktmuechecklist',
            name='wire_marking',
            field=models.CharField(choices=[('Не проверено', 'Не проверено'), ('Не используется', 'Не используется'), ('Принято', 'Принято'), ('Замечания', 'Замечания')], default='Не проверено', max_length=15, verbose_name='подключение кабелей питания к клеммным блокам, маркировка жил'),
        ),
        migrations.AlterField(
            model_name='ktmuechecklist',
            name='wire_ts_marking',
            field=models.CharField(choices=[('Не проверено', 'Не проверено'), ('Не используется', 'Не используется'), ('Принято', 'Принято'), ('Замечания', 'Замечания')], default='Не проверено', max_length=15, verbose_name='подключение кабелей ТС к клеммным блокам, маркировка жил'),
        ),
        migrations.AlterField(
            model_name='ktmuechecklist',
            name='wire_ty_marking',
            field=models.CharField(choices=[('Не проверено', 'Не проверено'), ('Не используется', 'Не используется'), ('Принято', 'Принято'), ('Замечания', 'Замечания')], default='Не проверено', max_length=15, verbose_name='подключение кабелей ТУ к клеммным блокам, маркировка жил'),
        ),
        migrations.AlterField(
            model_name='rm6checklist',
            name='cable_220',
            field=models.CharField(choices=[('Не проверено', 'Не проверено'), ('Не используется', 'Не используется'), ('Принято', 'Принято'), ('Замечания', 'Замечания')], default='Не проверено', max_length=15, verbose_name='подключение кабелей питания ≈220 В VIP от ШСН'),
        ),
        migrations.AlterField(
            model_name='rm6checklist',
            name='cable_24',
            field=models.CharField(choices=[('Не проверено', 'Не проверено'), ('Не используется', 'Не используется'), ('Принято', 'Принято'), ('Замечания', 'Замечания')], default='Не проверено', max_length=15, verbose_name='подключение кабелей питания =24 В flair от КТМ'),
        ),
        migrations.AlterField(
            model_name='rm6checklist',
            name='cable_earth',
            field=models.CharField(choices=[('Не проверено', 'Не проверено'), ('Не используется', 'Не используется'), ('Принято', 'Принято'), ('Замечания', 'Замечания')], default='Не проверено', max_length=15, verbose_name='соединение экранов кабелей связи отдельных участков в единую цепь'),
        ),
        migrations.AlterField(
            model_name='rm6checklist',
            name='cable_ts',
            field=models.CharField(choices=[('Не проверено', 'Не проверено'), ('Не используется', 'Не используется'), ('Принято', 'Принято'), ('Замечания', 'Замечания')], default='Не проверено', max_length=15, verbose_name='подключение кабелей ТС(правильность, маркировка'),
        ),
        migrations.AlterField(
            model_name='rm6checklist',
            name='cable_wire',
            field=models.CharField(choices=[('Не проверено', 'Не проверено'), ('Не используется', 'Не используется'), ('Принято', 'Принято'), ('Замечания', 'Замечания')], default='Не проверено', max_length=15, verbose_name='подключение кабелей связи к клммам модуля связи (правильность, маркировка'),
        ),
        migrations.AlterField(
            model_name='rm6checklist',
            name='earth_disable_RM6',
            field=models.CharField(choices=[('Не проверено', 'Не проверено'), ('Не используется', 'Не используется'), ('Принято', 'Принято'), ('Замечания', 'Замечания')], default='Не проверено', max_length=15, verbose_name='отсутствие заземления экранов в RM6'),
        ),
        migrations.AlterField(
            model_name='rm6checklist',
            name='passed',
            field=models.CharField(choices=[('НЕ принято', 'НЕ принято'), ('Принято', 'Принято')], default='NO', max_length=15, verbose_name='Чек лист RM6 прошел все проверки'),
        ),
        migrations.AlterField(
            model_name='rm6checklist',
            name='ts_rm6_controller',
            field=models.CharField(choices=[('Не проверено', 'Не проверено'), ('Не используется', 'Не используется'), ('Принято', 'Принято'), ('Замечания', 'Замечания')], default='Не проверено', max_length=15, verbose_name='проверка прохождения ТС от RM6 до дискретных входов контроллера'),
        ),
        migrations.AlterField(
            model_name='rm6checklist',
            name='ty_rm6_KTMUE',
            field=models.CharField(choices=[('Не проверено', 'Не проверено'), ('Не используется', 'Не используется'), ('Принято', 'Принято'), ('Замечания', 'Замечания')], default='Не проверено', max_length=15, verbose_name='проверка прохождения ТУ от RM6 до КТМиУЭ'),
        ),
        migrations.AlterField(
            model_name='rm6checklist',
            name='wire_patch',
            field=models.CharField(choices=[('Не проверено', 'Не проверено'), ('Не используется', 'Не используется'), ('Принято', 'Принято'), ('Замечания', 'Замечания')], default='Не проверено', max_length=15, verbose_name='подключение патч-кордов от модуля связи к VIP, flair'),
        ),
        migrations.AlterField(
            model_name='sktmchecklist',
            name='UZIP',
            field=models.CharField(choices=[('Не проверено', 'Не проверено'), ('Не используется', 'Не используется'), ('Принято', 'Принято'), ('Замечания', 'Замечания')], default='Не проверено', max_length=15, verbose_name='УЗИП'),
        ),
        migrations.AlterField(
            model_name='sktmchecklist',
            name='antenna_GPRS',
            field=models.CharField(choices=[('Не проверено', 'Не проверено'), ('Не используется', 'Не используется'), ('Принято', 'Принято'), ('Замечания', 'Замечания')], default='Не проверено', max_length=15, verbose_name='антенна GPS'),
        ),
        migrations.AlterField(
            model_name='sktmchecklist',
            name='antenna_GSM',
            field=models.CharField(choices=[('Не проверено', 'Не проверено'), ('Не используется', 'Не используется'), ('Принято', 'Принято'), ('Замечания', 'Замечания')], default='Не проверено', max_length=15, verbose_name='антенна GSM'),
        ),
        migrations.AlterField(
            model_name='sktmchecklist',
            name='antennas_bracket',
            field=models.CharField(choices=[('Не проверено', 'Не проверено'), ('Не используется', 'Не используется'), ('Принято', 'Принято'), ('Замечания', 'Замечания')], default='Не проверено', max_length=15, verbose_name='кронштейны крепления антенн'),
        ),
        migrations.AlterField(
            model_name='sktmchecklist',
            name='cable_24',
            field=models.CharField(choices=[('Не проверено', 'Не проверено'), ('Не используется', 'Не используется'), ('Принято', 'Принято'), ('Замечания', 'Замечания')], default='Не проверено', max_length=15, verbose_name='система питания =24В (в т.ч. предохранители в блоке батарей)'),
        ),
        migrations.AlterField(
            model_name='sktmchecklist',
            name='connections',
            field=models.CharField(choices=[('Не проверено', 'Не проверено'), ('Не используется', 'Не используется'), ('Принято', 'Принято'), ('Замечания', 'Замечания')], default='Не проверено', max_length=15, verbose_name='автоматы, переключатели и предохранители согласно схеме'),
        ),
        migrations.AlterField(
            model_name='sktmchecklist',
            name='controller',
            field=models.CharField(choices=[('Не проверено', 'Не проверено'), ('Не используется', 'Не используется'), ('Принято', 'Принято'), ('Замечания', 'Замечания')], default='Не проверено', max_length=15, verbose_name='контроллер'),
        ),
        migrations.AlterField(
            model_name='sktmchecklist',
            name='passed',
            field=models.CharField(choices=[('НЕ принято', 'НЕ принято'), ('Принято', 'Принято')], default='NO', max_length=15, verbose_name='Чек лист ШКТМ прошел все проверки'),
        ),
        migrations.AlterField(
            model_name='sktmchecklist',
            name='terminal_blocks',
            field=models.CharField(choices=[('Не проверено', 'Не проверено'), ('Не используется', 'Не используется'), ('Принято', 'Принято'), ('Замечания', 'Замечания')], default='Не проверено', max_length=15, verbose_name='блоки клемм'),
        ),
        migrations.AlterField(
            model_name='srtmchecklist',
            name='connections',
            field=models.CharField(choices=[('Не проверено', 'Не проверено'), ('Не используется', 'Не используется'), ('Принято', 'Принято'), ('Замечания', 'Замечания')], default='Не проверено', max_length=15, verbose_name='автоматы и предохранители согласно схеме'),
        ),
        migrations.AlterField(
            model_name='srtmchecklist',
            name='creit',
            field=models.CharField(choices=[('Не проверено', 'Не проверено'), ('Не используется', 'Не используется'), ('Принято', 'Принято'), ('Замечания', 'Замечания')], default='Не проверено', max_length=15, verbose_name='крейт расширения'),
        ),
        migrations.AlterField(
            model_name='srtmchecklist',
            name='passed',
            field=models.CharField(choices=[('НЕ принято', 'НЕ принято'), ('Принято', 'Принято')], default='NO', max_length=15, verbose_name='Чек лист ШРТМ прошел все проверки'),
        ),
        migrations.AlterField(
            model_name='srtmchecklist',
            name='terminal_blocks',
            field=models.CharField(choices=[('Не проверено', 'Не проверено'), ('Не используется', 'Не используется'), ('Принято', 'Принято'), ('Замечания', 'Замечания')], default='Не проверено', max_length=15, verbose_name='блоки клемм'),
        ),
        migrations.AlterField(
            model_name='suchecklist',
            name='passed',
            field=models.CharField(choices=[('НЕ принято', 'НЕ принято'), ('Принято', 'Принято')], default='NO', max_length=15, verbose_name='Чек лист ШУ прошел все проверки'),
        ),
        migrations.AlterField(
            model_name='suchecklist',
            name='py',
            field=models.CharField(choices=[('Не проверено', 'Не проверено'), ('Не используется', 'Не используется'), ('Принято', 'Принято'), ('Замечания', 'Замечания')], default='Не проверено', max_length=15, verbose_name='ПУ - расположение тип напряжение, ток, дата поверки, маркировка'),
        ),
        migrations.AlterField(
            model_name='suchecklist',
            name='py_number',
            field=models.CharField(choices=[('Не проверено', 'Не проверено'), ('Не используется', 'Не используется'), ('Принято', 'Принято'), ('Замечания', 'Замечания')], default='Не проверено', max_length=15, verbose_name='ПУ - количество'),
        ),
        migrations.AlterField(
            model_name='suchecklist',
            name='rs485_box',
            field=models.CharField(choices=[('Не проверено', 'Не проверено'), ('Не используется', 'Не используется'), ('Принято', 'Принято'), ('Замечания', 'Замечания')], default='Не проверено', max_length=15, verbose_name='распределительные коробки RS485 (количество, комплектность)'),
        ),
        migrations.AlterField(
            model_name='suchecklist',
            name='test_block',
            field=models.CharField(choices=[('Не проверено', 'Не проверено'), ('Не используется', 'Не используется'), ('Принято', 'Принято'), ('Замечания', 'Замечания')], default='Не проверено', max_length=15, verbose_name='испытательные колодки (количество+резерв, комплектность, правильность расключения, надежность крепления проводников, маркировка)'),
        ),
        migrations.AlterField(
            model_name='suchecklist',
            name='wire',
            field=models.CharField(choices=[('Не проверено', 'Не проверено'), ('Не используется', 'Не используется'), ('Принято', 'Принято'), ('Замечания', 'Замечания')], default='Не проверено', max_length=15, verbose_name='подключение измерительных цепей (правильность, маркировка, надежность)'),
        ),
        migrations.AlterField(
            model_name='suchecklist',
            name='wire_connection',
            field=models.CharField(choices=[('Не проверено', 'Не проверено'), ('Не используется', 'Не используется'), ('Принято', 'Принято'), ('Замечания', 'Замечания')], default='Не проверено', max_length=15, verbose_name='подключение кабелей связи (расключение в РИ, подключение к ПУ, то-пология согласно структурной схеме, маркировка)'),
        ),
        migrations.AlterField(
            model_name='suchecklist',
            name='wire_helper',
            field=models.CharField(choices=[('Не проверено', 'Не проверено'), ('Не используется', 'Не используется'), ('Принято', 'Принято'), ('Замечания', 'Замечания')], default='Не проверено', max_length=15, verbose_name='вспомогательные цепи (освещения, обогрева))'),
        ),
        migrations.AlterField(
            model_name='suchecklist',
            name='wire_reserve',
            field=models.CharField(choices=[('Не проверено', 'Не проверено'), ('Не используется', 'Не используется'), ('Принято', 'Принято'), ('Замечания', 'Замечания')], default='Не проверено', max_length=15, verbose_name='подключение цепей резервного питания'),
        ),
        migrations.AlterField(
            model_name='tmchecklist',
            name='passed',
            field=models.CharField(choices=[('НЕ принято', 'НЕ принято'), ('Принято', 'Принято')], default='NO', max_length=15, verbose_name='Чек лист телемеханики прошел все проверки'),
        ),
        migrations.AlterField(
            model_name='ybpchecklist',
            name='passed',
            field=models.CharField(choices=[('НЕ принято', 'НЕ принято'), ('Принято', 'Принято')], default='NO', max_length=15, verbose_name='Чек лист УВР прошел все проверки'),
        ),
        migrations.AlterField(
            model_name='ybpchecklist',
            name='ts_connector',
            field=models.CharField(choices=[('Не проверено', 'Не проверено'), ('Не используется', 'Не используется'), ('Принято', 'Принято'), ('Замечания', 'Замечания')], default='Не проверено', max_length=15, verbose_name='подключение цепей ТС вводного выключателя'),
        ),
        migrations.AlterField(
            model_name='ybpchecklist',
            name='ts_disconnector',
            field=models.CharField(choices=[('Не проверено', 'Не проверено'), ('Не используется', 'Не используется'), ('Принято', 'Принято'), ('Замечания', 'Замечания')], default='Не проверено', max_length=15, verbose_name='подключение цепей ТС секционного разъединителя'),
        ),
        migrations.AlterField(
            model_name='ybpchecklist',
            name='tt',
            field=models.CharField(choices=[('Не проверено', 'Не проверено'), ('Не используется', 'Не используется'), ('Принято', 'Принято'), ('Замечания', 'Замечания')], default='Не проверено', max_length=15, verbose_name='трансформаторы тока вводного выключателя (тип, номинал, класс точности, направление Л1-Л2)'),
        ),
        migrations.AlterField(
            model_name='ybpchecklist',
            name='tt_earth_ol',
            field=models.CharField(choices=[('Не проверено', 'Не проверено'), ('Не используется', 'Не используется'), ('Принято', 'Принято'), ('Замечания', 'Замечания')], default='Не проверено', max_length=15, verbose_name='заземление вторичных обмоток ТТ отходящих линий'),
        ),
        migrations.AlterField(
            model_name='ybpchecklist',
            name='tt_earth_vv',
            field=models.CharField(choices=[('Не проверено', 'Не проверено'), ('Не используется', 'Не используется'), ('Принято', 'Принято'), ('Замечания', 'Замечания')], default='Не проверено', max_length=15, verbose_name='заземление вторичных обмоток ТТ вводного выключателя'),
        ),
        migrations.AlterField(
            model_name='ybpchecklist',
            name='tt_lines',
            field=models.CharField(choices=[('Не проверено', 'Не проверено'), ('Не используется', 'Не используется'), ('Принято', 'Принято'), ('Замечания', 'Замечания')], default='Не проверено', max_length=15, verbose_name='трансформаторы тока отходящих линий (тип, номинал, класс точности, направление Л1-Л2)'),
        ),
        migrations.AlterField(
            model_name='ybpchecklist',
            name='tt_number',
            field=models.CharField(choices=[('Не проверено', 'Не проверено'), ('Не используется', 'Не используется'), ('Принято', 'Принято'), ('Замечания', 'Замечания')], default='Не проверено', max_length=15, verbose_name='Соответствие количества трансформаторов тока проекту'),
        ),
        migrations.AlterField(
            model_name='ybpchecklist',
            name='vire_ol',
            field=models.CharField(choices=[('Не проверено', 'Не проверено'), ('Не используется', 'Не используется'), ('Принято', 'Принято'), ('Замечания', 'Замечания')], default='Не проверено', max_length=15, verbose_name='подключение измерительных цепей тока и напряжения ОЛ(надежность подключения, маркировка, полярность И1-И2)'),
        ),
        migrations.AlterField(
            model_name='ybpchecklist',
            name='wire_vv',
            field=models.CharField(choices=[('Не проверено', 'Не проверено'), ('Не используется', 'Не используется'), ('Принято', 'Принято'), ('Замечания', 'Замечания')], default='Не проверено', max_length=15, verbose_name='подключение измерительных цепей тока и напряжения ВВ(надежность подключения, маркировка, полярность И1-И2)'),
        ),
    ]
