# Generated by Django 3.1.1 on 2020-11-13 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otk', '0031_auto_20201113_0943'),
    ]

    operations = [
        migrations.AddField(
            model_name='otkorder',
            name='substation_type',
            field=models.CharField(choices=[('БКТП', 'БКТП')], default='БКТП', max_length=15, verbose_name='Тип подстанции'),
        ),
    ]
