# Generated by Django 3.1.1 on 2020-11-13 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otk', '0032_otkorder_substation_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otkorder',
            name='rm_number',
            field=models.IntegerField(default=4),
        ),
        migrations.AlterField(
            model_name='otkorder',
            name='su_number',
            field=models.IntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='otkorder',
            name='ybp_number',
            field=models.IntegerField(default=2),
        ),
    ]
