# Generated by Django 3.1.1 on 2020-11-17 08:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('otk', '0033_auto_20201113_1137'),
    ]

    operations = [
        migrations.CreateModel(
            name='Checklist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=40)),
            ],
            options={
                'db_table': 'checklist',
            },
        ),
        migrations.CreateModel(
            name='ChListSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=40)),
                ('checklist', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='otk.checklist')),
            ],
            options={
                'db_table': 'chlistsection',
            },
        ),
        migrations.CreateModel(
            name='YseNoChoisePoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=40)),
                ('choice', models.CharField(choices=[('НЕ принято', 'НЕ принято'), ('Принято', 'Принято')], default='НЕ принято', max_length=15)),
                ('checklist', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='otk.chlistsection')),
            ],
            options={
                'db_table': 'yesno_choise_point',
            },
        ),
        migrations.CreateModel(
            name='StringPoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=40)),
                ('string', models.CharField(blank=True, default='', max_length=100)),
                ('checklist', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='otk.chlistsection')),
            ],
            options={
                'db_table': 'string_point',
            },
        ),
        migrations.CreateModel(
            name='FourChoisePoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=40)),
                ('choice', models.CharField(choices=[('Не проверено', 'Не проверено'), ('Не используется', 'Не используется'), ('Принято', 'Принято'), ('Замечания', 'Замечания')], default='Не проверено', max_length=15)),
                ('checklist', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='otk.chlistsection')),
            ],
            options={
                'db_table': 'four_choise_point',
            },
        ),
        migrations.AddField(
            model_name='otkorder',
            name='bm_checklist',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='otk.checklist'),
        ),
    ]
