# Generated by Django 3.1.1 on 2020-11-17 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otk', '0034_auto_20201117_1125'),
    ]

    operations = [
        migrations.AddField(
            model_name='fourchoisepoint',
            name='comment',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Коментарий'),
        ),
        migrations.AlterField(
            model_name='checklist',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='chlistsection',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='fourchoisepoint',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='stringpoint',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='ysenochoisepoint',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
