# Generated by Django 3.1.1 on 2020-11-17 11:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('otk', '0035_auto_20201117_1446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chlistsection',
            name='checklist',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='otk.checklist'),
        ),
        migrations.AlterField(
            model_name='fourchoisepoint',
            name='checklist',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='otk.chlistsection'),
        ),
        migrations.AlterField(
            model_name='stringpoint',
            name='checklist',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='otk.chlistsection'),
        ),
        migrations.AlterField(
            model_name='ysenochoisepoint',
            name='checklist',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='otk.chlistsection'),
        ),
    ]
