# Generated by Django 3.1.1 on 2020-11-17 13:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('otk', '0036_auto_20201117_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otkorder',
            name='bm_checklist',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='otk.checklist'),
        ),
        migrations.AlterField(
            model_name='otkorder',
            name='tm_checklist',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='otk.tmchecklist'),
        ),
    ]
