# Generated by Django 3.1.1 on 2020-11-17 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('otk', '0037_auto_20201117_1616'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='fourchoisepoint',
            table='fourchoisepoint',
        ),
        migrations.AlterModelTable(
            name='ysenochoisepoint',
            table='yesnochoisepoint',
        ),
    ]
