# Generated by Django 3.1.1 on 2020-11-17 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('otk', '0038_auto_20201117_1702'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='YseNoChoisePoint',
            new_name='YesNoChoisePoint',
        ),
    ]
