# Generated by Django 3.1.1 on 2020-11-18 06:48

from django.db import migrations, models
import django.db.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('otk', '0039_auto_20201117_1705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otkorder',
            name='bm_checklist',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.fields.NOT_PROVIDED, to='otk.checklist'),
        ),
        migrations.AlterField(
            model_name='otkorder',
            name='tm_checklist',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.fields.NOT_PROVIDED, to='otk.tmchecklist'),
        ),
    ]
