# Generated by Django 3.1.1 on 2020-11-18 06:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('otk', '0040_auto_20201118_0948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otkorder',
            name='bm_checklist',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='otk.checklist'),
        ),
        migrations.AlterField(
            model_name='otkorder',
            name='tm_checklist',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='otk.tmchecklist'),
        ),
    ]
