# Generated by Django 3.1.1 on 2020-11-18 07:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('otk', '0041_auto_20201118_0950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fourchoisepoint',
            name='checklist',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='otk.chlistsection'),
        ),
        migrations.AlterField(
            model_name='stringpoint',
            name='checklist',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='otk.chlistsection'),
        ),
        migrations.AlterField(
            model_name='yesnochoisepoint',
            name='checklist',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='otk.chlistsection'),
        ),
    ]
