# Generated by Django 3.1.1 on 2020-11-20 08:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('otk', '0044_auto_20201120_1110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chlistsection',
            name='checklist',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chlistsection', to='otk.checklist'),
        ),
    ]
