# Generated by Django 3.1.1 on 2020-11-20 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('otk', '0046_auto_20201120_1115'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='stringpoint',
            table='stringpoint',
        ),
    ]
