# Generated by Django 3.1.1 on 2020-11-23 07:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('otk', '0047_auto_20201120_2125'),
    ]

    operations = [
        migrations.AddField(
            model_name='otkorder',
            name='el_checklist',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='el_checklist', to='otk.checklist'),
        ),
        migrations.AlterField(
            model_name='otkorder',
            name='bm_checklist',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bm_checklist', to='otk.checklist'),
        ),
    ]
