# Generated by Django 3.1.1 on 2020-11-23 08:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('otk', '0048_auto_20201123_1022'),
    ]

    operations = [
        migrations.AddField(
            model_name='otkorder',
            name='doc_checklist',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='doc_checklist', to='otk.checklist'),
        ),
        migrations.AddField(
            model_name='otkorder',
            name='sal_checklist',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sal_checklist', to='otk.checklist'),
        ),
        migrations.AddField(
            model_name='otkorder',
            name='zip_checklist',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='zip_checklist', to='otk.checklist'),
        ),
    ]
