# Generated by Django 3.1.1 on 2020-11-23 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otk', '0049_auto_20201123_1123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yesnochoisepoint',
            name='choice',
            field=models.CharField(choices=[('Y', 'ДА'), ('N', 'НЕТ')], default='N', max_length=15),
        ),
    ]
