# Generated by Django 3.1.1 on 2020-11-23 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otk', '0050_auto_20201123_2133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yesnochoisepoint',
            name='choise',
            field=models.CharField(choices=[('Принято', 'ДА'), ('НЕ Принято', 'НЕТ')], default='НЕ Принято', max_length=15),
        ),
    ]
