# Generated by Django 3.1.1 on 2020-11-24 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('otk', '0053_auto_20201124_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otkorder',
            name='bm_checklist',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bm_checklist', to='otk.checklist'),
        ),
        migrations.AlterField(
            model_name='otkorder',
            name='doc_checklist',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='doc_checklist', to='otk.checklist'),
        ),
        migrations.AlterField(
            model_name='otkorder',
            name='el_checklist',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='el_checklist', to='otk.checklist'),
        ),
        migrations.AlterField(
            model_name='otkorder',
            name='sal_checklist',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sal_checklist', to='otk.checklist'),
        ),
        migrations.AlterField(
            model_name='otkorder',
            name='tm_checklist',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='otk.tmchecklist'),
        ),
        migrations.AlterField(
            model_name='otkorder',
            name='zip_checklist',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='zip_checklist', to='otk.checklist'),
        ),
    ]
