# Generated by Django 3.1.1 on 2020-11-24 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('otk', '0055_auto_20201124_1627'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='otkorder',
            name='rm_number',
        ),
        migrations.RemoveField(
            model_name='otkorder',
            name='su_number',
        ),
        migrations.RemoveField(
            model_name='otkorder',
            name='substation_type',
        ),
        migrations.RemoveField(
            model_name='otkorder',
            name='ybp_number',
        ),
    ]
