# Generated by Django 3.1.1 on 2020-11-24 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otk', '0056_auto_20201124_1629'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FourChoisePoint',
            new_name='FourChoicePoint',
        ),
        migrations.RemoveField(
            model_name='yesnochoisepoint',
            name='choice',
        ),
        migrations.AddField(
            model_name='yesnochoisepoint',
            name='choice',
            field=models.CharField(choices=[('Принято', 'ДА'), ('НЕ Принято', 'НЕТ')], default='НЕ Принято', max_length=15),
        ),
    ]
