# Generated by Django 3.1.1 on 2020-11-24 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('otk', '0057_auto_20201124_1833'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='fourchoicepoint',
            table='fourchoicepoint',
        ),
        migrations.AlterModelTable(
            name='yesnochoisepoint',
            table='yesnochoicepoint',
        ),
    ]
