# Generated by Django 3.1.1 on 2020-11-25 09:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('otk', '0058_auto_20201124_1836'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderConfigSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='otk.otkorder')),
            ],
            options={
                'db_table': 'orderconfigsection',
            },
        ),
    ]
