# Generated by Django 3.1.1 on 2020-11-25 11:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('otk', '0059_orderconfigsection'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderconfigsection',
            name='order',
        ),
        migrations.AddField(
            model_name='otkorder',
            name='config_section',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='config_section', to='otk.orderconfigsection'),
        ),
    ]
