# Generated by Django 3.1.1 on 2020-11-25 12:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('otk', '0060_auto_20201125_1442'),
    ]

    operations = [
        migrations.AddField(
            model_name='fourchoicepoint',
            name='order_config',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='otk.orderconfigsection'),
        ),
        migrations.AddField(
            model_name='integerpoint',
            name='order_config',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='otk.orderconfigsection'),
        ),
        migrations.AddField(
            model_name='stringpoint',
            name='order_config',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='otk.orderconfigsection'),
        ),
        migrations.AddField(
            model_name='substationtypepoint',
            name='order_config',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='otk.orderconfigsection'),
        ),
        migrations.AddField(
            model_name='yesnochoisepoint',
            name='order_config',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='otk.orderconfigsection'),
        ),
        migrations.AlterField(
            model_name='otkorder',
            name='config_section',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='config_section', to='otk.orderconfigsection'),
        ),
    ]
